## Glossary

anecdotal evidence: Evidence, often personal, that is collected casually rather than by a well-designed study.

population: A group we are interested in studying, often a group of people, but the term is also used for animals, vegetables and minerals.

cross-sectional study: A study that collects data about a population at a particular point in time.

longitudinal study: A study that follows a population over time, collecting data from the same group repeatedly.
respondent: A person who responds to a survey.

cohort: A group of respondents

sample: The subset of a population used to collect data.

representative: A sample is representative if every member of the population has the same chance of being in the sample.

oversampling: The technique of increasing the representation of a sub-population in order to avoid errors due to small sample sizes.

record: In a database, a collection of information about a single person or other object of study.

field: In a database, one of the named variables that makes up a record.

table: In a database, a collection of records.

raw data: Values collected and recorded with little or no checking, calculation or interpretation.

recode: A value that is generated by calculation and other logic applied to raw data.

summary statistic: The result of a computation that reduces a dataset to a single number (or at least a smaller set of numbers) that captures some characteristic of the data.

apparent effect: A measurement or summary statistic that suggests that something interesting is happening.

statistically significant: An apparent effect is statistically significant if it is unlikely to occur by chance.

artifact: An apparent effect that is caused by bias, measurement error, or some other kind of error.

Sensitivity: The probability that the test is positive given the subject has the disease P(+ | D).

Specificity: The probability that the test is negative given that the subject does not have the disease P(-|Dc).

Prevalence: The marginal probability of the disease P(D).

If we know the prevalence, sensitivity and specificity of the tests. We can calculate the:

* Positive predictive value P(D|+)
* Negative predictive value P(Dc|-)

_Independence_ of events is the idea that events are unrelated. Two events A and B are independent if P(A and B) = P(A)P(B). Equivalently P(A given B) = P(A). 

alpha α refers to the likelihood that the true population parameter lies outside the confidence interval. Usually expressed as a proportion. Thus if the confidence level is 95%, α would be 5% or 0.05. In hypothesis testing α refers to significance level, the probability of making a 'type 1' error.

beta β is the probability of a type II error, that is, accepting the null hypothesis when it is actually false. 
power is (1 - β)

Z score is something to do with the percentile, related to the _standard_ normal distribution.

Percentile and Quantiles:

If you were the 95th percentile then 95% of people scored worse and 5% scored better. This is the quantile (though usually the quantile is 0.95).

Sample quantiles estimate the population quantile. So the 95th quantile is the point x such that:

    CDF(x) = 0.95
    
The population _median_ is the 50th percentile.

Percentiles are not probabilities, they are values from the population. So the the 80th percentile of a set of heights might be 70 inches. And that height is the height where 80% of the set are on or less than that height.